### ISSUE TITLE
Das & Zeichen in email einer Adresse führt zu einem Fehler

### ISSUE THREAD

**Issue by axelrathey** [blacksenator/carddav2fb#3]
Hallo zusammen,
Habe schon länger das Problem, dass eine email Adresse von meinen Kontakten ein &-zeichen enthält. Bei diesem Kontakt wird dann im terminal von carddav2fb immer ein Fehler ausgegeben und diese email Adresse ist dann nicht im Telefonbuch.
Habe heute mal upgedatet auf die aktuelle version. Nach einigem hin und her mit neuen erforderlichen PHP-Versionen ist dieser alte Fehler aber weiterhin da.

Folgende Anzeige kommt da vom Script:

Contact without phone numbers will be skipped
PHP Warning: SimpleXMLElement::addChild(): unterminated entity reference nicole@xxxxxx.de in /volume1/homes/admin/carddav2fb/src/FritzBox/Converter.php on line 153

Warning: SimpleXMLElement::addChild(): unterminated entity reference nicole@xxxxxx.de in /volume1/homes/admin/carddav2fb/src/FritzBox/Converter.php on line 153
PHP Warning: SimpleXMLElement::addChild(): unterminated entity reference nicole@xxxxxx.de in /volume1/homes/admin/carddav2fb/src/FritzBox/Converter.php on line 153

Warning: SimpleXMLElement::addChild(): unterminated entity reference nicole@xxxxxx.de in /volume1/homes/admin/carddav2fb/src/FritzBox/Converter.php on line 153
Contact without phone numbers will be skipped

Tatsächlich lautet die emails aber christian&nicole@xxxxxx.de
Die domain habe ich wegen Datenschutz auf xxxxx gesetzt. Ich vermute irgendeine Problem beim Bearbeiten der Zeichenkette mit der emailadresse aufgrund des &-Zeichens. Habe mal geschaut im Internet findet man unterschiedliche Angaben dazu ob &-Zeichen in der email Adresse erlaubt sind.

Es wäre daher schön, wenn carddav2fb auch Adressen mit &-Zeichen unterstützen würde.

Danke, viele Grüße
Axel

**Comment by blacksenator** [comment]
Moved to [the parent fork](https://github.com/andig/carddav2fb/issues/222)
