### ISSUE TITLE
export for Grandstream GRP2612 not working

### ISSUE THREAD

**Issue by linuzer** [blacksenator/carddav2fb#6]
The produced XML cannot be imported into a Grandstream GRP2612, because the AdressBook-attribute has a spell-error (-> AddressBook).

I will submit a PR.

**Comment by blacksenator** [comment]
merged

**Comment by blacksenator** [comment]
@linuzer Sorry: took a few days before I rebased andigs master. Now both of your changes are in this fork. Sorry for delay

**Comment by linuzer** [comment]
No problem at all, I had the changes also offline. 
But thanks for merging, so now I can switch back to the official master.
